[package]
name = "revm_fzz"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
revm-interpreter = { git = "https://github.com/bluealloy/revm", branch = "release/v50" }
